Repository nyudlts/ultraviolet, pull requests merged in 2021-10, with the labels that each got.

#93 Feature/app versioning footer cleanup
  .uv-version
  assets/less/site/globals/site.overrides
  assets/less/theme.less
  invenio.cfg
  templates/semantic-ui/invenio_app_rdm/footer.html
Labels: enhancement, chore

#90 Add 'Browse all' header button
  Pipfile
  templates/semantic-ui/invenio_app_rdm/footer.html
  templates/semantic-ui/invenio_app_rdm/header.html
  tests/ui/test_front_view.py
Labels: enhancement

#96 Docs/imagemagick link test 86 94
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
  docs/Gemfile
  docs/Gemfile.lock
  docs/Rakefile
  docs/favicon.ico
  docs/get-started/dev-docker-setup.md
Labels: chore

#100 adds in a couple reminders and corrections for documentation
  docs/get-started/dev-docker-setup.md
Labels: documentation
