Repository nyudlts/ultraviolet, pull requests merged in 2021-09, with the labels that each got.

#71 Chore/py3 8 node14 69
  .github/workflows/test.yml
  .gitignore
  .invenio
  .nvmrc
  .python-version
  Pipfile
  Pipfile.lock
  docs/getting-started/dev-docker-setup.md
Labels: chore

#74 Chore/py3 8 node14 69
  .github/workflows/test.yml
  .gitignore
  .nvmrc
  .python-version
  Pipfile
  Pipfile.lock
  docs/getting-started/dev-docker-setup.md
Labels: bug, chore

#78 chores: update project deps / docker / docs
  .gitignore
  .invenio
  Dockerfile
  Pipfile.lock
  docs/getting-started/dev-docker-setup.md
  docs/getting-started/updating-versions.md
Labels: chore

#80 Docs npm postgres 76 79
  docs/development/add-fixtures.md
  docs/development/index.md
  docs/development/look-feel.md
  docs/getting-started/dev-docker-setup.md
Labels: documentation
